[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "c51e993e13c54399f15224cfe51a14e76258e920"
os = "macos"

    [[lazygit.download]]
    sha256 = "be6c6a88f3214aed6f09354dc279ddd4f7560ab788c484ca888876f24f279564"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.aarch64-apple-darwin.tar.gz"
[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "a9330e20600adab2ec316acfec7fa80af2642275"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "379fdd2580b9ff84ed9a9a4eb0fb3d41f0044b221080e5bcde2b2a8570828ba8"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.aarch64-linux-gnu.tar.gz"
[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "a9330e20600adab2ec316acfec7fa80af2642275"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "379fdd2580b9ff84ed9a9a4eb0fb3d41f0044b221080e5bcde2b2a8570828ba8"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.aarch64-linux-musl.tar.gz"
[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "f7aa680e2a00d2aaf41cfb83b3536dab8b46fb6a"
os = "freebsd"

    [[lazygit.download]]
    sha256 = "7713fe605bcdb1b33d4c2a6e83d5a84556712444ace6bdec8c253ed231e81b1c"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.aarch64-unknown-freebsd.tar.gz"
[[lazygit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3e8a6e7a7cde8022a0e70266d73babf511db97f2"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "02b6df7d4e3e165b4f061f2f5a8ab6535aff70bf4c2ef9f2e7e7eb2804eae259"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.armv6l-linux-gnueabihf.tar.gz"
[[lazygit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3e8a6e7a7cde8022a0e70266d73babf511db97f2"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "02b6df7d4e3e165b4f061f2f5a8ab6535aff70bf4c2ef9f2e7e7eb2804eae259"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.armv6l-linux-musleabihf.tar.gz"
[[lazygit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "664328bda1ed1e8684599f36e6d902361ec696bd"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "6597f8646dcd3f7b45c0a9eca2d09cc41d23eb95f8ae9d1abafe74aa93b72dfc"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.armv7l-linux-gnueabihf.tar.gz"
[[lazygit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "664328bda1ed1e8684599f36e6d902361ec696bd"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "6597f8646dcd3f7b45c0a9eca2d09cc41d23eb95f8ae9d1abafe74aa93b72dfc"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.armv7l-linux-musleabihf.tar.gz"
[[lazygit]]
arch = "i686"
git-tree-sha1 = "d4b8a49c427f1f64ea4e20039db417a073bc57d5"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "1148f6e032e9ace04ef0e4a7e3c0c2a7108ae4147fb369e621506135693717eb"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.i686-linux-gnu.tar.gz"
[[lazygit]]
arch = "i686"
git-tree-sha1 = "d4b8a49c427f1f64ea4e20039db417a073bc57d5"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "1148f6e032e9ace04ef0e4a7e3c0c2a7108ae4147fb369e621506135693717eb"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.i686-linux-musl.tar.gz"
[[lazygit]]
arch = "i686"
git-tree-sha1 = "f02d97b2d00c5de4ef18694aea52495249186060"
os = "windows"

    [[lazygit.download]]
    sha256 = "0133667cde21e3a9baaa0c58a97bf708783c574fbd35521153a3525ec0724f93"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.i686-w64-mingw32.tar.gz"
[[lazygit]]
arch = "powerpc64le"
git-tree-sha1 = "015b5fb34d5609e896d08a8cbaad66764829b89d"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "d08f08c4baf87e3d5c78784bf242eafe647310701e1c61b327ce0047bc2b111e"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.powerpc64le-linux-gnu.tar.gz"
[[lazygit]]
arch = "riscv64"
git-tree-sha1 = "2d60ab2d75d6cdbbc60c191d12695e9138edb250"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "bab286d922d4e583c9922e624ff6803386ae7268742e34b9411c860a4130f7ce"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.riscv64-linux-gnu.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "d30985168ef85afbe5b57b743b4ef113c65b4253"
os = "macos"

    [[lazygit.download]]
    sha256 = "a6ed0670fb04f9bde6abd380316ac1b988c4c312d368fa488759146b1d87dea1"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.x86_64-apple-darwin.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "18270273c59eb583b4af7515d1e78b70a4de7c5a"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "ea59843fd37a761f48fbab0a080d894d40462bc8ceabca9272b9a681303ff093"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.x86_64-linux-gnu.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "4c6ed4ec9653a3f894ac283e9d1a40f85882e55d"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "5d4224a3ebad0b50fedf6c712e13f4934932c192b0dde9d9a86be1830daddf8e"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.x86_64-linux-musl.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "fa05659b42540964aae52a047781463b0c1a0bf2"
os = "freebsd"

    [[lazygit.download]]
    sha256 = "18316e9b2836a53617fd67f3f5a47341bde87d3fbbba5fffb6e912200eef4d68"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.x86_64-unknown-freebsd.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "841f859abccfcd165224cdfb260df7eb7c503e43"
os = "windows"

    [[lazygit.download]]
    sha256 = "c331d224104a265f0275723dfd966fc2e0f7567844fec6c6fd644f687c737cd5"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.61.1+0/lazygit.v0.61.1.x86_64-w64-mingw32.tar.gz"
