[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "c3f4ae0d0a9ff7529a47a7c7decd7c98e51fb444"
os = "macos"

    [[lazygit.download]]
    sha256 = "80ceadebe2900622b21206293c966af9ee3b78f2ecb099df0c07e85d70514f67"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.aarch64-apple-darwin.tar.gz"
[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "9f241bef34a67c38add7c28b15fbb3c40db9f937"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "f2fbe5d1ac8e9b4508e7407d9fc912574e97a51ed008180dcb816e515bae2ce8"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.aarch64-linux-gnu.tar.gz"
[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "9f241bef34a67c38add7c28b15fbb3c40db9f937"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "f2fbe5d1ac8e9b4508e7407d9fc912574e97a51ed008180dcb816e515bae2ce8"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.aarch64-linux-musl.tar.gz"
[[lazygit]]
arch = "aarch64"
git-tree-sha1 = "67802254aa7517bedb3dcd1480dba99eeba51f0a"
os = "freebsd"

    [[lazygit.download]]
    sha256 = "3aa6b9a111bb4fa144bba389f8a20ddbf78d08da448c3d96a074f0b13f04bc9d"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.aarch64-unknown-freebsd.tar.gz"
[[lazygit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60ce1f5967980542723b9f940d7a278e1d111104"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "ddba9954475383b362cd7fa9710be506d1a0a1c1442e8a6f5129986ea2cf0c71"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.armv6l-linux-gnueabihf.tar.gz"
[[lazygit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60ce1f5967980542723b9f940d7a278e1d111104"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "ddba9954475383b362cd7fa9710be506d1a0a1c1442e8a6f5129986ea2cf0c71"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.armv6l-linux-musleabihf.tar.gz"
[[lazygit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0273e9a6b47ce232acb8b8d3613c89062443c1fe"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "ad0bbf2b20c5df108e6e072d32273988d6edc8c7fbefe421a1f0277c15842d11"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.armv7l-linux-gnueabihf.tar.gz"
[[lazygit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0273e9a6b47ce232acb8b8d3613c89062443c1fe"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "ad0bbf2b20c5df108e6e072d32273988d6edc8c7fbefe421a1f0277c15842d11"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.armv7l-linux-musleabihf.tar.gz"
[[lazygit]]
arch = "i686"
git-tree-sha1 = "98c8e6ca8aef1c67390793338b2999dbfd953029"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "756e0a1bea7b1e0a0a53dcc3bbb45758120ff9521ea6a40e62880aa1f6a06853"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.i686-linux-gnu.tar.gz"
[[lazygit]]
arch = "i686"
git-tree-sha1 = "98c8e6ca8aef1c67390793338b2999dbfd953029"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "756e0a1bea7b1e0a0a53dcc3bbb45758120ff9521ea6a40e62880aa1f6a06853"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.i686-linux-musl.tar.gz"
[[lazygit]]
arch = "i686"
git-tree-sha1 = "0cfa120e7da85f4e1d2e36c35dd0f556eeba2f04"
os = "windows"

    [[lazygit.download]]
    sha256 = "6e5ccdaa09403c73d00e144f78ec3f0d2ce1cd233fd617fca83e11f9f1eae2b4"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.i686-w64-mingw32.tar.gz"
[[lazygit]]
arch = "powerpc64le"
git-tree-sha1 = "34e033e878a4cee89a2cfbf5b227a63d739d4712"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "77c312438ea28bad4710805120eaa8e654a40ea8973fff3eda2089e68e60a97e"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.powerpc64le-linux-gnu.tar.gz"
[[lazygit]]
arch = "riscv64"
git-tree-sha1 = "ac817de72baaf2378c45a57c6b78981330aa366d"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "47b40cf77fae890325018db430e5991c074892fabb7fcc34fb806f21ec9f5c07"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.riscv64-linux-gnu.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "3ddf4870f46b42f48563a73057f3f5262361bf86"
os = "macos"

    [[lazygit.download]]
    sha256 = "7173514c8c2983755001e9207578d8c23ad04e94b805425323f8bfc78e42bce2"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.x86_64-apple-darwin.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "c2ffc132aed3351f3fadbb7c23a23f76edece309"
libc = "glibc"
os = "linux"

    [[lazygit.download]]
    sha256 = "b65c9fe735d99bb1bfb628cd7234a50c78bccd2cdc432336fdcc6f4f6c2e62a6"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.x86_64-linux-gnu.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "4f768752c99418f89816b77635bbf66d4b336c13"
libc = "musl"
os = "linux"

    [[lazygit.download]]
    sha256 = "670aea6266d9c5a8c38763f11d13a96985c59d160d47c33cc61d457da4ebc334"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.x86_64-linux-musl.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "77dfb36feb16bee14a5351c9f67a533a8aef20d2"
os = "freebsd"

    [[lazygit.download]]
    sha256 = "50ce9a6904e4a5f131d883df8c1cf688840b8d9e7a92a37939b2553db35dd388"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.x86_64-unknown-freebsd.tar.gz"
[[lazygit]]
arch = "x86_64"
git-tree-sha1 = "02e2c97feac1f8d44fb124756ad7bbb16bedba01"
os = "windows"

    [[lazygit.download]]
    sha256 = "1a3c76f080fdeb13548c9328655e87fa039d5188062aa622d9644d8e327c923b"
    url = "https://github.com/JuliaBinaryWrappers/lazygit_jll.jl/releases/download/lazygit-v0.65.0+0/lazygit.v0.65.0.x86_64-w64-mingw32.tar.gz"
